"""EOR landing page content. Short, plain, US spelling."""
from content_common import src
VIDEO_ID = "ZtBkp85XGCM"
EOR_V2={
 "slug":"employer-of-record-india","hub":"eor","nav":"Employer of Record","nav_short":"EOR India","crumb":"Employer of Record India","type":"eor_v2",
 "title":"Employer of Record India | Hire in India Without Setting Up an Entity | Paybooks, a TransPerfect company",
 "description":"Hire in India without setting up a company. Paybooks becomes the legal employer, runs payroll and every government filing, and guarantees no penalties. $199 per employee per month. Start in 10 working days.",
 "service_type":"Employer of Record services, India","area":"India",
 "h1":"Hire in India *without setting up an entity.*",
 "sub":"Access top talent in India with Paybooks as your Employer of Record (EOR). For your first 50 hires, we serve as the legal employer and handle payroll and government filings, backed by a written no-penalty guarantee. You keep control of your team and IP, with the option to set up your own entity later.",
 "facts":[("3,000+","customers onboarded"),("$199","per employee per month, all-in"),("10 days","from offer to first day"),("12 years","running Indian payroll"),("1.5M+","paychecks processed a year")],
 "cta":"Get a quote for a role","cta2":"Talk to an EOR expert",
 "fit":{"h2":"Is an Employer of Record right for you?","sub":"Find your situation below to see which way of hiring fits you best.",
  "head":["If you have","Best option","Why it fits","Not recommended"],
  "rows":[["1 to 20 hires, no entity","<b>Employer of Record</b>","Live in 10 days. No setup cost.","Contractors for full-time roles"],
          ["Contractors working full time for you","<b>EOR conversion</b>","Removes the risk of treating employees as contractors","Leaving them as contractors"],
          ["Sales leaders who sign contracts","<b>Managed India Office</b>","Staff who sign contracts create a tax risk under any EOR","EOR"],
          ["20 to 50 people and growing","<b>EOR now, your own entity within a year</b>","Owning an entity gets cheaper in this range","Staying on a $599 to $699 EOR"],
          ["50+ people, or IP-heavy work","<b>Managed India Office</b>","Cheaper per head. IP held in your name.","EOR at any price"]],
  "cap":None},
 "experience":{"h2":"What your hire sees","sub":"The offer letter, benefits, and support your new hire gets from day one.",
  "offer":{"title":"Offer of employment","lines":[("Employer","Paybooks Technologies India Pvt Ltd, a TransPerfect company"),("Deployed to","[Your company] · Engineering"),("Designation","Senior Software Engineer"),("Annual pay","$26,000 (basic pay $13,000), paid monthly in rupees"),("Benefits","Health cover for the family, provident fund, gratuity, 24 days of leave"),("Probation · Notice","6 months · 60 days"),("IP","Assigned to [Your company]"),("Start date","Within 10 working days")],"draft":"Draft. Paybooks to supply the live template."},
  "cards":[("Your name on the letter","Paybooks is the employer. Your company, manager, and role are on page one."),
           ("Real benefits from day one","Health insurance, provident fund, gratuity, and paid leave. Payslips and tax forms in one app."),
           ("Ready on day one","Laptop shipped before the start date. A welcome call with you and our HR team."),
           ("Stock options and raises","Your equity plan can cover them. Raises and bonuses go through in the next payroll, no fee."),
           ("Their LinkedIn profile","They list your company as their employer. We explain how Paybooks shows up before the offer."),
           ("Help in their time zone","Our Bengaluru HR desk answers their payslip, insurance, and leave questions.")],
  "video_h":"Paybooks in 51 seconds","video_p":"Payroll, legal compliance, and employee experience, from the Paybooks channel. A two-minute EOR walkthrough (what the candidate signs, what you approve, what we file) is recommended to replace it before launch."},
 "control":{"h2":"You manage the work. We handle the employer duties.","sub":"Exactly who handles what, as written in your service agreement.",
  "you":{"h3":"You decide","items":[("Who to hire and what to pay","We quote the full monthly cost first"),("Day-to-day work, reviews, promotions","Managers are yours"),("Work hours, leave, and remote rules","Your policies apply"),("Raises, bonuses, equity","Processed next payroll, no fee"),("When to part ways","We handle it under Indian law"),("When to own your entity","We set it up. Nothing restarts.")]},
  "us":{"h3":"We take care of","items":[("The employment contract and legal liability","Under Indian labor law"),("Payroll and every government payment","Provident fund, insurance, taxes: we calculate, file, and pay"),("Registrations and inspections","With every government office"),("Benefits","Insurance enrollment, claims, leave, expenses"),("Exits and final pay","Notice, gratuity, tax forms"),("Data security","ISO 27001, SOC 2 Type II, data hosted in India")]}},
 "compliance":{"h2":"Compliance as a clause","sub":"Our no-penalty promise is written into your contract, not just our website.",
  "clause":"<b>No-penalty guarantee.</b> If we file or pay anything late or wrong for your employees, we pay the interest, fees, and penalties, and fix it within five working days.",
  "cards":[("Every payroll law, covered","Provident fund, state insurance, professional tax, income tax withholding, labor welfare fund, gratuity, and the Labour Codes. In every state your people work in."),
           ("Filed on time, by chartered accountants","A named chartered accountant on your account owns every deadline. Deductions follow the latest rules."),
           ("We pay the government directly","You never receive a tax bill to pay. No gap for a penalty to grow in."),
           ("Monthly proof","What was filed, when, with receipt numbers. Your auditor can use it."),
           ("Registrations, inspections, advice","We register you with the provident fund, insurance, tax, and labor departments, represent you in inspections, and advise on pay structure."),
           ("Tax risk and IP","We flag roles that create tax risk before you hire. IP is assigned to you.")]},
 "cost":{"h2":"What it costs, line by line","sub":"Move the sliders to see the full monthly cost of an India hire, line by line.",
  "cmp_head":["","Paybooks","Deel","Remote","Multiplier","India-only startups"],
  "cmp_rows":[["Monthly fee per employee","<b>$199</b>","$599","$699","about $459 to $499","$99"],["Currency markup","None","Reported 1 to 3%","Reported 1 to 3%","Reported 1 to 3%","Varies"],["Pays the government directly","<b>Yes</b>","Through a local partner","Through a local partner","Through a local partner","Varies"],["No-penalty guarantee in writing","<b>Yes</b>","No","No","No","No"],["Parent company","TransPerfect, $1.32B","Venture-backed","Venture-backed","Venture-backed","Varies"],["Path to your own entity","<b>We set it up for you</b>","Start over","Start over","Start over","Start over"]],
  "cmp_cap":"Fees published September 23, 2026: "+src("Deel","https://www.deel.com/pricing/")+", "+src("Remote","https://remote.com/pricing")+", "+src("Multiplier","https://remotepeople.com/blog/employer-of-record-cost/")+", "+src("Wisemonk","https://www.wisemonk.io/pricing")+"."},
 "exits":{"h2":"Clean exits, whenever you need them","sub":"Letting one person go, or moving your team to your own entity. We handle both.",
  "tl_a":{"h3":"Letting someone go","items":[("Day 0","You decide. We confirm notice, usually 30 to 90 days."),("Day 1 to 3","We issue the termination letter under Indian law. Notice, or pay in place of notice."),("Last day","Final pay: salary, unused leave, gratuity if due."),("After","Provident fund transfer, relieving letter, and laptop return.")]},
  "tl_b":{"h3":"Moving to your own Indian entity","items":[("Decide","Usually at 20 to 50 people. We set up and run the entity, or hand it to your team."),("Weeks 1 to 12","Your entity is set up. New hires keep joining through us."),("Switch day","Contracts move over. Provident fund and gratuity continue. Same payslip app."),("After","Same payroll team, now for your entity. Give us 30 days' notice to end the EOR.")]}},
 "service":{"h2":"How we work with you","sub":"One team, one monthly report, and one invoice for your whole India team.","cards":[("One account manager","With a chartered accountant behind them."),("Reply within one working day","India hours, with US and UK overlap for calls."),("One monthly report","Payroll summary, filing proof, and cost in your currency."),("One invoice","In USD, GBP, or EUR at the bank rate. Salary, government costs, and our fee."),("Integrations","Employee and cost data flows to your HR or finance system. Single sign-on for the employee app."),("Security","ISO 27001:2022. SOC 2 Type II. Data hosted in India.")]},
 "timeline":{"h2":"Ten working days to a first day","sub":"What happens between offer and first day.","items":[("Day 0 to 2","You approve the package. We issue the contract."),("Day 2 to 4","Your hire signs. We collect their documents."),("Day 4 to 7","We complete government registrations and ship the laptop."),("Day 5 to 8","Background check complete."),("Day 7 to 10","First day."),("Monthly","Salary paid on your date. Filings done by the 7th and 15th. You get the proof and the invoice.")]},
 "proof":{"h2":"India depth. Global parent. Published price.",
  "cards":[("Twelve years of doing this","3,000+ employers. 1.5 million paychecks a year. $1B+ in salaries paid.",["Provident fund","Insurance","Payroll tax","Labour Codes","28 states"]),
           ("A $1.32 billion parent","TransPerfect bought Paybooks in 2024. 150+ cities. 10,000+ clients. 90% of the Fortune 500.",["ISO 27001:2022","SOC 2 Type II","GDPR","G2 4.5"])],
  "stats":[("3,000+","employers since 2012"),("1.5M+","paychecks a year"),("$1B+","salaries paid a year"),("150+","TransPerfect cities")],
  "logos_note":"Two client references: to be supplied by Paybooks."},
 "faq":[("Is it legal for a foreign company to hire in India this way?","Yes. Paybooks is an Indian company that employs your staff under Indian law and provides their services to you."),
  ("Will senior candidates accept a Paybooks contract?","Yes. Your company, manager, and role are on the letter. Benefits match a good Indian employer. We brief every candidate first."),
  ("What does it really cost?","Salary, plus about 12 to 17% in government costs, plus $199. The calculator above shows every line."),
  ("Does this create tax risk for my company?","It lowers it. Risk rises only if your India team signs contracts on your behalf. We flag those roles before you hire."),
  ("Can EOR employees get our stock options?","Yes, through a grant letter from your company."),
  ("How does termination work in India?","Notice is usually 30 to 90 days, or pay in place of notice. Gratuity is due after one year. We handle the process and the final pay."),
  ("What happens when we set up our own Indian entity?","We set it up and run it if you want. Contracts move over. Provident fund and gratuity continue."),
  ("Who owns the IP?","You do. It is assigned to you in the contracts."),
  ("Which states do you cover?","All of India.")],
 "cta_h":"Send us one role. Get the whole picture back.","cta_p":"Role, city, and pay. Within two working days you get the full monthly cost, the contract terms, the start date, and a sample offer letter.",
}
