import html, json, re
def esc(s): return html.escape(s, quote=True)
def accent(h1): return re.sub(r"\*(.+?)\*", r"<em>\1</em>", esc(h1))
CHECK='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12l5 5L20 7"/></svg>'
ALERT='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 9v4m0 4h.01M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0z"/></svg>'
ROUTE='''<svg class="route" viewBox="0 0 600 520" fill="none" aria-hidden="true">
<defs><linearGradient id="g1" x1="0" x2="1"><stop offset="0" stop-color="#7FA36A" stop-opacity=".0"/><stop offset=".5" stop-color="#4F8A10"/><stop offset="1" stop-color="#F26B1D"/></linearGradient></defs>
<circle cx="120" cy="420" r="78" stroke="#C9D8BE" stroke-width="1.5"/><path d="M60 400c30-10 60 8 90-4s40-30 62-22" stroke="#C9D8BE" stroke-width="1.5"/><path d="M78 452c26 6 54-6 84 6" stroke="#C9D8BE" stroke-width="1.5"/>
<path d="M150 380C230 250 340 170 470 130" stroke="url(#g1)" stroke-width="2.5" stroke-dasharray="6 8"/>
<circle cx="470" cy="130" r="6" fill="#F26B1D"/><circle cx="470" cy="130" r="14" stroke="#F26B1D" stroke-opacity=".35"/><circle cx="470" cy="130" r="24" stroke="#F26B1D" stroke-opacity=".15"/>
</svg>'''
PIN='<div class="pin" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0z"/><circle cx="12" cy="10" r="3"/></svg></div>'
def table(head,rows,cap=None,hl=None):
    th="".join(f'<th{" class=hl" if hl==i else ""}>{esc(h)}</th>' for i,h in enumerate(head))
    tr="".join("<tr>"+"".join(f'<td{" class=hl" if hl==i else ""}>{c}</td>' for i,c in enumerate(row))+"</tr>" for row in rows)
    return f'<div class="t-wrap"><table class="tbl"><thead><tr>{th}</tr></thead><tbody>{tr}</tbody></table></div>'+(f'<p class="fine">{cap}</p>' if cap else "")
def render_eor(p, r, C, video_id):
    hero_cards_unused=('<div class="empwrap"><div class="emp">'
                '<div class="emp-top"><span class="av">AR</span><div><b>Ananya R.</b><span>Senior Software Engineer · Bengaluru</span></div><span class="pill">Compliant</span></div>'
                '<div class="emp-meta"><div><span>Employer of record</span><b>Paybooks, a TransPerfect company</b></div><div><span>Works for</span><b>[Your company]</b></div><div><span>Started</span><b>10 working days after offer</b></div></div>'
                '<ul class="emp-rows"><li><span>Salary paid</span><b>Sep 1</b></li><li><span>Provident fund filed</span><b>Sep 14</b></li><li><span>Tax deposited</span><b>Sep 6</b></li><li><span>Health cover</span><b>Active</b></li><li><span>Penalties</span><b>₹0</b></li></ul>'
                '<div class="emp-foot"><span>All-in cost this month</span><b>$2,700</b></div>'
                '</div></div>')
    facts="".join(f"<li><b>{esc(v)}</b>{esc(l)}</li>" for v,l in p["facts"])
    logo_imgs="".join(f'<span class="gchip"><img src="{r}assets/logos-t/l{i:02d}.png" alt="Paybooks client logo"></span>' for i in range(1,24) if i!=2)
    hero_cards=('<div class="vidhold" role="img" aria-label="Video placeholder"><div class="vh-frame">'
                '<span class="vh-mini"><svg width="16" height="16" viewBox="0 0 24 24" fill="#fff"><path d="M8 5v14l11-7z"/></svg></span><span class="vh-cap"><b>How Paybooks EOR works</b><small>2-minute walkthrough</small></span><span class="vh-tag">Video</span></div></div>')
    hero=(f'<section class="hero v2"><div class="wrap"><div class="grid"><div><span class="cta2-tag hero-tag">Your first India hire, live within days</span><h1>{accent(p["h1"])}</h1><p class="sub">{p["sub"]}</p>'
          f'<div class="btns"><a class="btn" href="{r}contact.html">{esc(p["cta"])}</a><a class="btn ghost" href="{r}contact.html">{esc(p["cta2"])}</a></div><ul class="cta2-ticks hero-ticks"><li>No entity setup cost</li><li>“No penalties ever” promise</li><li>From $199 per employee a month</li></ul></div>'
          f'{hero_cards}</div></div></section><div class="trust"><div class="wrap tr-sp tr-j"><p class="tr-lab">Trusted by<br><b>3,000+</b> companies</p><i class="tr-dv"></i><div class="tr-mq" aria-label="Paybooks clients"><div class="tr-track">{logo_imgs}{logo_imgs}</div></div></div></div>'
          f'')
    subnav=''
    f=p["fit"]
    fit=f'<section class="sec" id="fit"><div class="wrap"><div class="head rv"><span class="num">01</span><div><span class="eyebrow">Start here</span><h2>{esc(f["h2"])}</h2><p>{f["sub"]}</p></div></div>{table(f["head"],f["rows"],f.get("cap"),1)}</div></section>'
    e=p["experience"]; o=e["offer"]
    offer=(f'<div class="letter"><div class="lt-head"><span class="lt-brand"><img src="{r}assets/mark.png" alt="" width="30" height="30"><span><b>paybooks</b><small>A TransPerfect company</small></span></span><span class="lt-kind">{esc(o["title"])}<small>Ref. PB-EOR-0925 · Bengaluru</small></span></div>'
           f'<div class="lt-title"><span class="eyebrow">Dear Ananya,</span><h5>{esc(o["lines"][2][1])}</h5><p>{esc(o["lines"][1][1])}</p></div>'
           '<dl class="lt-fields">'+"".join(f'<div><dt>{esc(k)}</dt><dd>{esc(v)}</dd></div>' for k,v in o["lines"] if k not in ("Designation","Deployed to"))+'</dl>'
           f'<div class="lt-sign"><div><i></i><b>For Paybooks Technologies India Pvt Ltd</b><small>Authorized signatory</small></div><div><i class="empty"></i><b>Accepted by candidate</b><small>Signature and date</small></div></div>'
           f'</div>')
    video=(f'<div class="vid" data-id="{video_id}"><button class="vid-face" type="button" aria-label="Play video: {esc(e["video_h"])}">'
           f'<img src="{r}assets/video-thumb.jpg" alt="" width="1280" height="720"><span class="vid-play"><svg width="26" height="26" viewBox="0 0 24 24" fill="#fff"><path d="M8 5v14l11-7z"/></svg></span>'
           f'<span class="vid-cap"><b>{esc(e["video_h"])}</b><small>0:51 · Paybooks YouTube</small></span></button></div>' if video_id else
           f'<div style="margin-top:22px;border-radius:16px;background:linear-gradient(135deg,var(--forest),#1B5232);color:#fff;padding:28px;display:grid;grid-template-columns:56px 1fr;gap:18px;align-items:center"><span style="width:56px;height:56px;border-radius:50%;background:var(--orange);display:grid;place-items:center"><svg width="22" height="22" viewBox="0 0 24 24" fill="#fff"><path d="M8 5v14l11-7z"/></svg></span><div><b style="font-family:var(--head);font-size:18px">{esc(e["video_h"])}</b><p style="color:#BFD3B9;font-size:14px;margin-top:4px">{esc(e["video_p"])}</p></div></div>')
    exp_cards="".join(f'<li class="card"><div class="ic">{CHECK}</div><h3>{esc(h)}</h3><p>{t}</p></li>' for h,t in e["cards"])
    experience=(f'<section class="sec alt" id="experience"><div class="wrap"><div class="head rv"><span class="num">02</span><div><h2>{esc(e["h2"])}</h2><p>{e["sub"]}</p></div></div>'
                f'<div class="split"><div class="sticky">{offer}</div><ul class="cards" style="grid-template-columns:1fr 1fr">{exp_cards}</ul></div></div></section>')
    c=p["control"]
    def col(cls,d): return f'<div class="col {cls}"><h3>{esc(d["h3"])}</h3><ul>'+"".join(f'<li><div><b>{esc(a)}</b><span>{esc(b)}</span></div></li>' for a,b in d["items"])+'</ul></div>'
    control=f'<section class="sec" id="control"><div class="wrap"><div class="head rv"><span class="num">03</span><div><span class="eyebrow">Who does what</span><h2>{esc(c["h2"])}</h2><p>{c["sub"]}</p></div></div><div class="raci">{col("you",c["you"])}{col("us",c["us"])}</div><div class="midcta"><div><b>Want to see it in writing?</b><span>We will share a sample service agreement with your quote.</span></div><div class="btns"><a class="btn" href="#faq">Get a quote for a role</a><a class="btn ghost" href="#faq">Talk to an EOR expert</a></div></div></div></section>'
    k=p["compliance"]
    comp_cards="".join(f'<li class="card"><div class="ic">{CHECK}</div><h3>{esc(h)}</h3><p>{t}</p></li>' for h,t in k["cards"])
    compliance=f'<section class="sec alt" id="compliance"><div class="wrap"><div class="head rv"><span class="num">04</span><div><span class="eyebrow">No penalties</span><h2>{esc(k["h2"])}</h2>{("<p>"+k["sub"]+"</p>") if k.get("sub") else ""}</div></div><div class="clause">{k["clause"]}</div><ul class="cards three" style="margin-top:24px">{comp_cards}</ul></div></section>'
    co=p["cost"]
    calc=('<div class="calc calc2"><div class="calc-in"><h3>India employee cost calculator</h3><p class="calc-note">Based on September 2026 rules. This is an estimate. Your written quote is final.</p>'
          '<label>Annual pay (USD) <span id="ctcv"></span></label><input id="ctc" type="range" min="6000" max="100000" step="500" value="26000">'
          '<label>Employees <span id="nv"></span></label><input id="n" type="range" min="1" max="100" step="1" value="5">'
          '<div class="calc-row"><label>State</label><select id="st"><option value="200">Karnataka (about $2 professional tax)</option><option value="200">Maharashtra (about $2 professional tax)</option><option value="0">Delhi / Haryana (no professional tax)</option><option value="200">Telangana (about $2 professional tax)</option><option value="208">Tamil Nadu (about $2 professional tax)</option></select></div><div class="calc-row"><label>Our fee</label><span class="fee-pill">$199 per employee a month</span></div>'
          '</div>'
          '<div class="calc-out"><div class="kpis"><div class="kpi"><b id="o_total"></b><span>per employee per month</span></div><div class="kpi"><b id="o_usd"></b><span id="o_usd_l">a year for your team</span></div><div class="kpi"><b id="o_stat"></b><span>government costs on top of salary</span></div></div>'
          '<ul class="lines" id="o_rows"></ul>'
          '<p class="fine">Provident fund 12% of basic pay (half of gross). Gratuity 15 days of basic a year. State insurance 3.25% under $220 a month. Converted at ₹95.7 per $1 (Sep 23, 2026). Sources: <a href="https://mercans.com/glossary/employees-provident-fund-epf-contribution/" rel="nofollow">Provident fund office</a>, <a href="https://payroll.org/news-resources/news/news-detail/2025/12/17/india-s-new-labour-codes-are-in-force-payroll-teams-must-act" rel="nofollow">Labour Codes</a>.</p></div></div>'
          '<script>(function(){var fx=95.7,fee=199;var ctc=document.getElementById("ctc"),n=document.getElementById("n"),st=document.getElementById("st");var calm=matchMedia("(prefers-reduced-motion: reduce)").matches;function usd(x){return "$"+Math.round(x).toLocaleString("en-US")}function pct(x){return x.toFixed(1)+"%"}function tw(el,to,fmt){if(!el)return;var from=el._v==null?to:el._v;el._v=to;if(calm||from===to){el.textContent=fmt(to);return}var t0=null,d=420;if(el._raf)cancelAnimationFrame(el._raf);if(el._to)clearTimeout(el._to);el._to=setTimeout(function(){cancelAnimationFrame(el._raf);el.textContent=fmt(to)},d+80);function step(ts){if(!t0)t0=ts;var k=Math.min(1,(ts-t0)/d),e=1-Math.pow(1-k,3);el.textContent=fmt(from+(to-from)*e);if(k<1)el._raf=requestAnimationFrame(step)}el._raf=requestAnimationFrame(step)}var labels=["Gross salary","Provident fund (employer share)","Gratuity set aside","State insurance (if eligible)","Professional tax (withheld from pay)","Paybooks fee","Total per employee"];var ul=document.getElementById("o_rows"),cells=labels.map(function(l,i){var li=document.createElement("li");if(i==6)li.className="tot";var sp=document.createElement("span");sp.textContent=l;var b=document.createElement("b");li.appendChild(sp);li.appendChild(b);ul.appendChild(li);return b});function go(){var ua=+ctc.value,g=ua*fx/12,b=g*.5,pf=b*.12,gr=b*15/26/12,esi=g<=21000?g*.0325:0,pt=+st.value,f=fee*fx,tot=g+pf+gr+esi+f,statp=(pf+gr+esi)/g*100;document.getElementById("ctcv").textContent=usd(ua);document.getElementById("nv").textContent=n.value;tw(document.getElementById("o_total"),tot/fx,usd);tw(document.getElementById("o_usd"),tot/fx*12*n.value,usd);document.getElementById("o_usd_l").textContent="a year for "+n.value+(+n.value==1?" hire":" hires");tw(document.getElementById("o_stat"),statp,pct);[g,pf,gr,esi,pt,f,tot].forEach(function(v,i){tw(cells[i],v/fx,usd)})}[ctc,n,st].forEach(function(e){e.addEventListener("input",go)});go()})();</script>')
    cost=(f'<section class="sec" id="cost"><div class="wrap"><div class="head rv"><span class="num">05</span><div><span class="eyebrow">Cost</span><h2>{esc(co["h2"])}</h2><p>{co["sub"]}</p></div></div>'
          '<ul class="cparts"><li><span class="cp-n">1</span><div><b>Salary</b><p>The pay you agree with your hire, set in dollars. We pay it in rupees on your payroll date.</p></div></li><li><span class="cp-n">2</span><div><b>Government costs</b><p>Provident fund, gratuity and state insurance. Set by law, about 8 to 9% of salary for most roles, and the same with any provider.</p></div></li><li><span class="cp-n">3</span><div><b>Our fee</b><p>From $199 per employee a month, plus a one-time $50 onboarding fee.</p></div></li></ul>'
          f'{calc}</div></section>')
    compare=f'<section class="sec alt" id="compare"><div class="wrap"><div class="head rv"><span class="num">06</span><div><span class="eyebrow">Compare</span><h2>Compare EOR providers: Choose the best</h2><p>See how Paybooks compares on fees and setup.</p></div></div>{table(co["cmp_head"],co["cmp_rows"],None,1)}</div></section>'
    x=p["exits"]
    def tl(d): return f'<div><h3 style="margin-bottom:12px">{esc(d["h3"])}</h3><ul class="tl">'+"".join(f'<li><span class="d">{esc(a)}</span><div><p>{b}</p></div></li>' for a,b in d["items"])+'</ul></div>'
    exits=f'<section class="sec" id="exits"><div class="wrap"><div class="head rv"><span class="num">07</span><div><span class="eyebrow">Exits</span><h2>{esc(x["h2"])}</h2><p>{x["sub"]}</p></div></div><div class="split" style="grid-template-columns:1fr 1fr">{tl(x["tl_a"])}{tl(x["tl_b"])}</div></div></section>'
    s=p["service"]
    service=f'<section class="sec alt" id="service"><div class="wrap"><div class="head rv"><span class="num">08</span><div><span class="eyebrow">Working with us</span><h2>{esc(s["h2"])}</h2>{("<p>"+s["sub"]+"</p>") if s.get("sub") else ""}</div></div><ul class="cards three">'+"".join(f'<li class="card"><div class="ic">{CHECK}</div><h3>{esc(h)}</h3><p>{t}</p></li>' for h,t in s["cards"])+'</ul></div></section>'
    t=p["timeline"]
    timeline=f'<section class="sec tight" id="timeline"><div class="wrap"><div class="split"><div class="head rv"><span class="num">09</span><div><span class="eyebrow">Timeline</span><h2>{esc(t["h2"])}</h2>{("<p>"+t["sub"]+"</p>") if t.get("sub") else ""}</div></div><ul class="tl">'+"".join(f'<li><span class="d">{esc(a)}</span><div><p>{b}</p></div></li>' for a,b in t["items"])+'</ul></div></div></section>'
    pr=p["proof"]
    proof=(f'<section class="dark" id="proof"><div class="wrap"><div class="head rv"><span class="num">09</span><div><span class="eyebrow">Why Paybooks</span><h2>{esc(pr["h2"])}</h2></div></div><ul class="cards">'+"".join(f'<li class="card"><h3>{esc(a)}</h3><p>{b}</p><div class="chips">'+"".join(f"<span>{esc(z)}</span>" for z in ch)+'</div></li>' for a,b,ch in pr["cards"])+'</ul>'
           f'<div class="stats" style="margin-top:20px">'+"".join(f'<div class="stat"><b>{esc(v)}</b><span>{esc(l)}</span></div>' for v,l in pr["stats"])+f'</div><div class="logos"><span>Reference quote</span><span>Reference quote</span></div><p class="fine" style="color:#BFD3B9">{esc(pr["logos_note"])}</p></div></section>')
    faq=(f'<section class="sec alt" id="faq"><div class="wrap"><div class="faq"><div class="sticky"><span class="eyebrow">FAQ</span><h2>Your questions, answered</h2><p style="color:var(--muted);margin:14px 0 22px">What to know before you hire in India.</p><a class="btn" href="{r}contact.html">{esc(p["cta2"])}</a></div><div>'
         +"".join(f"<details><summary>{esc(q)}</summary><p>{a}</p></details>" for q,a in p["faq"])+'</div></div></div></section>')
    deeper=('<section class="sec alt"><div class="wrap"><div class="head"><span class="eyebrow">Go deeper</span><h2>Read more</h2></div><div class="deeper">'+"".join(f'<a href="{r}{q["slug"]}/"><h3>{esc(q["h1"])}</h3><p>{esc(q["description"])}</p></a>' for q in C.PAGES if q["slug"] in p.get("deeper",[]))+'</div></div></section>') if p.get("deeper") else ''
    cta=(f'<section class="cta2"><div class="wrap"><div class="cta2-card"><div class="cta2-copy"><span class="cta2-tag">Get started</span><h2>Your first India hire, <em>live within days.</em></h2>'
         '<p>Tell us the role, city, and pay. You get the full monthly cost in dollars, the contract terms and a start date. No commitment.</p>'
         f'<div class="btns"><a class="btn" href="{r}contact.html">{esc(p["cta"])}</a><a class="btn ghost" href="{r}contact.html">{esc(p["cta2"])}</a></div>'
         '<ul class="cta2-ticks"><li>No entity setup cost</li><li>“No penalties ever” promise</li><li>From $199 per employee a month</li></ul></div>'
         '<div class="cta2-quote" aria-hidden="true"><div class="q-head"><span>Your quote</span><em>Ready within days</em></div>'
         '<div class="q-role"><b>Senior Software Engineer</b><small>Bengaluru · $26,000 a year</small></div>'
         '<ul class="q-rows"><li><span>Monthly cost, all-in</span><b>$2,550</b></li><li><span>Government costs</span><b>$184</b></li><li><span>Paybooks fee</span><b>$199</b></li><li><span>Start date</span><b>Oct 13, 2026</b></li></ul>'
         '<div class="q-docs"><span>Contract terms</span><span>Sample offer letter</span></div></div></div></div></section>')
    js='<script>(function(){var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add("in");io.unobserve(e.target)}})},{threshold:.12});document.querySelectorAll(".rv,.cards .card,.stat,.raci .col,.clause,.tl li").forEach(function(el){el.classList.add("rv");io.observe(el)});var links=[].slice.call(document.querySelectorAll(".subnav a"));var secs=links.map(function(a){return document.querySelector(a.getAttribute("href"))}).filter(Boolean);var so=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){links.forEach(function(a){a.classList.toggle("on",a.getAttribute("href")==="#"+e.target.id)})}})},{rootMargin:"-40% 0px -55% 0px"});secs.forEach(function(s){so.observe(s)})})();</script>'
    return hero+subnav+fit+experience+control+compliance+cost+compare+exits+service+timeline+faq+deeper+cta+js
